import { FAB } from "@rneui/base";
import React, { useRef, useState } from "react";
import { FlatList, RefreshControl, StyleSheet, View } from "react-native";
import AppText from "../components/AppText";
import DailyForecast from "../components/DailyForecast";

export default function DailyForecastScreen({ route }) {
  const forecast = route.params.dailyForecast;
  const [refreshing, setRefreshing] = useState(false);
  const [fabVisible, setFabVisible] = useState(false);
  const listRef = useRef(null);
  // const sampleData = [
  //   {
  //     time: "2023-12-11T06:00:00Z",
  //     values: {
  //       cloudBaseAvg: 0.83,
  //       cloudBaseMax: 2.75,
  //       cloudBaseMin: 0,
  //       cloudCeilingAvg: 0.2,
  //       cloudCeilingMax: 1.43,
  //       cloudCeilingMin: 0,
  //       cloudCoverAvg: 45.97,
  //       cloudCoverMax: 100,
  //       cloudCoverMin: 0,
  //       dewPointAvg: 20.01,
  //       dewPointMax: 23.19,
  //       dewPointMin: 16.2,
  //       evapotranspirationAvg: 0.185,
  //       evapotranspirationMax: 0.612,
  //       evapotranspirationMin: 0.01,
  //       evapotranspirationSum: 4.25,
  //       freezingRainIntensityAvg: 0,
  //       freezingRainIntensityMax: 0,
  //       freezingRainIntensityMin: 0,
  //       humidityAvg: 68.67,
  //       humidityMax: 97.69,
  //       humidityMin: 36.33,
  //       iceAccumulationAvg: 0,
  //       iceAccumulationLweAvg: 0,
  //       iceAccumulationLweMax: 0,
  //       iceAccumulationLweMin: 0,
  //       iceAccumulationLweSum: 0,
  //       iceAccumulationMax: 0,
  //       iceAccumulationMin: 0,
  //       iceAccumulationSum: 0,
  //       moonriseTime: "2023-12-11T04:29:27Z",
  //       moonsetTime: "2023-12-11T16:33:34Z",
  //       precipitationProbabilityAvg: 0,
  //       precipitationProbabilityMax: 0,
  //       precipitationProbabilityMin: 0,
  //       pressureSurfaceLevelAvg: 979.78,
  //       pressureSurfaceLevelMax: 981.71,
  //       pressureSurfaceLevelMin: 976.78,
  //       rainAccumulationAvg: 0,
  //       rainAccumulationLweAvg: 0,
  //       rainAccumulationLweMax: 0,
  //       rainAccumulationLweMin: 0,
  //       rainAccumulationMax: 0,
  //       rainAccumulationMin: 0,
  //       rainAccumulationSum: 0,
  //       rainIntensityAvg: 0,
  //       rainIntensityMax: 0,
  //       rainIntensityMin: 0,
  //       sleetAccumulationAvg: 0,
  //       sleetAccumulationLweAvg: 0,
  //       sleetAccumulationLweMax: 0,
  //       sleetAccumulationLweMin: 0,
  //       sleetAccumulationLweSum: 0,
  //       sleetAccumulationMax: 0,
  //       sleetAccumulationMin: 0,
  //       sleetIntensityAvg: 0,
  //       sleetIntensityMax: 0,
  //       sleetIntensityMin: 0,
  //       snowAccumulationAvg: 0,
  //       snowAccumulationLweAvg: 0,
  //       snowAccumulationLweMax: 0,
  //       snowAccumulationLweMin: 0,
  //       snowAccumulationLweSum: 0,
  //       snowAccumulationMax: 0,
  //       snowAccumulationMin: 0,
  //       snowAccumulationSum: 0,
  //       snowIntensityAvg: 0,
  //       snowIntensityMax: 0,
  //       snowIntensityMin: 0,
  //       sunriseTime: "2023-12-11T06:06:00Z",
  //       sunsetTime: "2023-12-11T17:52:00Z",
  //       temperatureApparentAvg: 27.88,
  //       temperatureApparentMax: 33.98,
  //       temperatureApparentMin: 22.45,
  //       temperatureAvg: 27.15,
  //       temperatureMax: 33.43,
  //       temperatureMin: 22.45,
  //       uvHealthConcernAvg: 1,
  //       uvHealthConcernMax: 3,
  //       uvHealthConcernMin: 0,
  //       uvIndexAvg: 2,
  //       uvIndexMax: 8,
  //       uvIndexMin: 0,
  //       visibilityAvg: 10.74,
  //       visibilityMax: 12.5,
  //       visibilityMin: 7.33,
  //       weatherCodeMax: 1001,
  //       weatherCodeMin: 1001,
  //       windDirectionAvg: 188.24,
  //       windGustAvg: 3.23,
  //       windGustMax: 4.65,
  //       windGustMin: 1.25,
  //       windSpeedAvg: 1.44,
  //       windSpeedMax: 2.62,
  //       windSpeedMin: 0.38,
  //     },
  //   },
  //   {
  //     time: "2023-12-12T06:00:00Z",
  //     values: {
  //       cloudBaseAvg: 0.99,
  //       cloudBaseMax: 2.44,
  //       cloudBaseMin: 0,
  //       cloudCeilingAvg: 0.12,
  //       cloudCeilingMax: 2.53,
  //       cloudCeilingMin: 0,
  //       cloudCoverAvg: 26.97,
  //       cloudCoverMax: 100,
  //       cloudCoverMin: 0,
  //       dewPointAvg: 19.31,
  //       dewPointMax: 22.1,
  //       dewPointMin: 16.14,
  //       evapotranspirationAvg: 0.177,
  //       evapotranspirationMax: 0.6,
  //       evapotranspirationMin: 0.013,
  //       evapotranspirationSum: 4.064,
  //       freezingRainIntensityAvg: 0,
  //       freezingRainIntensityMax: 0,
  //       freezingRainIntensityMin: 0,
  //       humidityAvg: 65.57,
  //       humidityMax: 94.89,
  //       humidityMin: 36.77,
  //       iceAccumulationAvg: 0,
  //       iceAccumulationLweAvg: 0,
  //       iceAccumulationLweMax: 0,
  //       iceAccumulationLweMin: 0,
  //       iceAccumulationLweSum: 0,
  //       iceAccumulationMax: 0,
  //       iceAccumulationMin: 0,
  //       iceAccumulationSum: 0,
  //       moonriseTime: "2023-12-12T05:25:01Z",
  //       moonsetTime: "2023-12-12T17:27:38Z",
  //       precipitationProbabilityAvg: 0.2,
  //       precipitationProbabilityMax: 5,
  //       precipitationProbabilityMin: 0,
  //       pressureSurfaceLevelAvg: 979.83,
  //       pressureSurfaceLevelMax: 982.19,
  //       pressureSurfaceLevelMin: 977.16,
  //       rainAccumulationAvg: 0,
  //       rainAccumulationLweAvg: 0,
  //       rainAccumulationLweMax: 0.01,
  //       rainAccumulationLweMin: 0,
  //       rainAccumulationMax: 0.01,
  //       rainAccumulationMin: 0,
  //       rainAccumulationSum: 0.01,
  //       rainIntensityAvg: 0,
  //       rainIntensityMax: 0.01,
  //       rainIntensityMin: 0,
  //       sleetAccumulationAvg: 0,
  //       sleetAccumulationLweAvg: 0,
  //       sleetAccumulationLweMax: 0,
  //       sleetAccumulationLweMin: 0,
  //       sleetAccumulationLweSum: 0,
  //       sleetAccumulationMax: 0,
  //       sleetAccumulationMin: 0,
  //       sleetIntensityAvg: 0,
  //       sleetIntensityMax: 0,
  //       sleetIntensityMin: 0,
  //       snowAccumulationAvg: 0,
  //       snowAccumulationLweAvg: 0,
  //       snowAccumulationLweMax: 0,
  //       snowAccumulationLweMin: 0,
  //       snowAccumulationLweSum: 0,
  //       snowAccumulationMax: 0,
  //       snowAccumulationMin: 0,
  //       snowAccumulationSum: 0,
  //       snowIntensityAvg: 0,
  //       snowIntensityMax: 0,
  //       snowIntensityMin: 0,
  //       sunriseTime: "2023-12-12T06:06:00Z",
  //       sunsetTime: "2023-12-12T17:53:00Z",
  //       temperatureApparentAvg: 27.58,
  //       temperatureApparentMax: 33.57,
  //       temperatureApparentMin: 21.49,
  //       temperatureAvg: 27.02,
  //       temperatureMax: 33.26,
  //       temperatureMin: 21.49,
  //       uvHealthConcernAvg: 1,
  //       uvHealthConcernMax: 3,
  //       uvHealthConcernMin: 0,
  //       uvIndexAvg: 2,
  //       uvIndexMax: 9,
  //       uvIndexMin: 0,
  //       visibilityAvg: 10.94,
  //       visibilityMax: 12.35,
  //       visibilityMin: 7.63,
  //       weatherCodeMax: 1000,
  //       weatherCodeMin: 1000,
  //       windDirectionAvg: 188.4,
  //       windGustAvg: 2.25,
  //       windGustMax: 3.97,
  //       windGustMin: 0.27,
  //       windSpeedAvg: 0.82,
  //       windSpeedMax: 2.38,
  //       windSpeedMin: 0.07,
  //     },
  //   },
  //   {
  //     time: "2023-12-13T06:00:00Z",
  //     values: {
  //       cloudBaseAvg: 1.59,
  //       cloudBaseMax: 12.27,
  //       cloudBaseMin: 0,
  //       cloudCeilingAvg: 1.61,
  //       cloudCeilingMax: 12.52,
  //       cloudCeilingMin: 0,
  //       cloudCoverAvg: 13.42,
  //       cloudCoverMax: 99.22,
  //       cloudCoverMin: 0,
  //       dewPointAvg: 16.7,
  //       dewPointMax: 21.28,
  //       dewPointMin: 10.97,
  //       evapotranspirationAvg: 0.203,
  //       evapotranspirationMax: 0.653,
  //       evapotranspirationMin: 0.01,
  //       evapotranspirationSum: 4.676,
  //       freezingRainIntensityAvg: 0,
  //       freezingRainIntensityMax: 0,
  //       freezingRainIntensityMin: 0,
  //       humidityAvg: 59.52,
  //       humidityMax: 96.6,
  //       humidityMin: 28.46,
  //       iceAccumulationAvg: 0,
  //       iceAccumulationLweAvg: 0,
  //       iceAccumulationLweMax: 0,
  //       iceAccumulationLweMin: 0,
  //       iceAccumulationLweSum: 0,
  //       iceAccumulationMax: 0,
  //       iceAccumulationMin: 0,
  //       iceAccumulationSum: 0,
  //       moonriseTime: "2023-12-13T06:24:52Z",
  //       moonsetTime: "2023-12-13T18:27:04Z",
  //       precipitationProbabilityAvg: 0,
  //       precipitationProbabilityMax: 0,
  //       precipitationProbabilityMin: 0,
  //       pressureSurfaceLevelAvg: 979.29,
  //       pressureSurfaceLevelMax: 981.63,
  //       pressureSurfaceLevelMin: 976.79,
  //       rainAccumulationAvg: 0,
  //       rainAccumulationLweAvg: 0,
  //       rainAccumulationLweMax: 0,
  //       rainAccumulationLweMin: 0,
  //       rainAccumulationMax: 0,
  //       rainAccumulationMin: 0,
  //       rainAccumulationSum: 0,
  //       rainIntensityAvg: 0,
  //       rainIntensityMax: 0,
  //       rainIntensityMin: 0,
  //       sleetAccumulationAvg: 0,
  //       sleetAccumulationLweAvg: 0,
  //       sleetAccumulationLweMax: 0,
  //       sleetAccumulationLweMin: 0,
  //       sleetAccumulationLweSum: 0,
  //       sleetAccumulationMax: 0,
  //       sleetAccumulationMin: 0,
  //       sleetIntensityAvg: 0,
  //       sleetIntensityMax: 0,
  //       sleetIntensityMin: 0,
  //       snowAccumulationAvg: 0,
  //       snowAccumulationLweAvg: 0,
  //       snowAccumulationLweMax: 0,
  //       snowAccumulationLweMin: 0,
  //       snowAccumulationLweSum: 0,
  //       snowAccumulationMax: 0,
  //       snowAccumulationMin: 0,
  //       snowAccumulationSum: 0,
  //       snowIntensityAvg: 0,
  //       snowIntensityMax: 0,
  //       snowIntensityMin: 0,
  //       sunriseTime: "2023-12-13T06:06:00Z",
  //       sunsetTime: "2023-12-13T17:53:00Z",
  //       temperatureApparentAvg: 26.55,
  //       temperatureApparentMax: 31.6,
  //       temperatureApparentMin: 21.62,
  //       temperatureAvg: 26.77,
  //       temperatureMax: 32.81,
  //       temperatureMin: 21.62,
  //       uvHealthConcernAvg: 1,
  //       uvHealthConcernMax: 3,
  //       uvHealthConcernMin: 0,
  //       uvIndexAvg: 2,
  //       uvIndexMax: 8,
  //       uvIndexMin: 0,
  //       visibilityAvg: 11.36,
  //       visibilityMax: 12.55,
  //       visibilityMin: 8.88,
  //       weatherCodeMax: 1000,
  //       weatherCodeMin: 1000,
  //       windDirectionAvg: 138.46,
  //       windGustAvg: 3.22,
  //       windGustMax: 6.49,
  //       windGustMin: 0.84,
  //       windSpeedAvg: 1.54,
  //       windSpeedMax: 2.4,
  //       windSpeedMin: 0.62,
  //     },
  //   },
  //   {
  //     time: "2023-12-14T06:00:00Z",
  //     values: {
  //       cloudBaseAvg: 0.84,
  //       cloudBaseMax: 2.33,
  //       cloudBaseMin: 0,
  //       cloudCeilingAvg: 0.4,
  //       cloudCeilingMax: 3.14,
  //       cloudCeilingMin: 0,
  //       cloudCoverAvg: 16.5,
  //       cloudCoverMax: 62.29,
  //       cloudCoverMin: 0,
  //       dewPointAvg: 18.08,
  //       dewPointMax: 22.36,
  //       dewPointMin: 12.5,
  //       evapotranspirationAvg: 0.193,
  //       evapotranspirationMax: 0.607,
  //       evapotranspirationMin: 0.015,
  //       evapotranspirationSum: 4.43,
  //       freezingRainIntensityAvg: 0,
  //       freezingRainIntensityMax: 0,
  //       freezingRainIntensityMin: 0,
  //       humidityAvg: 60.8,
  //       humidityMax: 94.24,
  //       humidityMin: 27.63,
  //       iceAccumulationAvg: 0,
  //       iceAccumulationLweAvg: 0,
  //       iceAccumulationLweMax: 0,
  //       iceAccumulationLweMin: 0,
  //       iceAccumulationLweSum: 0,
  //       iceAccumulationMax: 0,
  //       iceAccumulationMin: 0,
  //       iceAccumulationSum: 0,
  //       moonriseTime: "2023-12-14T07:26:00Z",
  //       moonsetTime: "2023-12-14T19:29:02Z",
  //       precipitationProbabilityAvg: 0,
  //       precipitationProbabilityMax: 0,
  //       precipitationProbabilityMin: 0,
  //       pressureSurfaceLevelAvg: 979.79,
  //       pressureSurfaceLevelMax: 981.83,
  //       pressureSurfaceLevelMin: 976.46,
  //       rainAccumulationAvg: 0,
  //       rainAccumulationLweAvg: 0,
  //       rainAccumulationLweMax: 0,
  //       rainAccumulationLweMin: 0,
  //       rainAccumulationMax: 0,
  //       rainAccumulationMin: 0,
  //       rainAccumulationSum: 0,
  //       rainIntensityAvg: 0,
  //       rainIntensityMax: 0,
  //       rainIntensityMin: 0,
  //       sleetAccumulationAvg: 0,
  //       sleetAccumulationLweAvg: 0,
  //       sleetAccumulationLweMax: 0,
  //       sleetAccumulationLweMin: 0,
  //       sleetAccumulationLweSum: 0,
  //       sleetAccumulationMax: 0,
  //       sleetAccumulationMin: 0,
  //       sleetIntensityAvg: 0,
  //       sleetIntensityMax: 0,
  //       sleetIntensityMin: 0,
  //       snowAccumulationAvg: 0,
  //       snowAccumulationLweAvg: 0,
  //       snowAccumulationLweMax: 0,
  //       snowAccumulationLweMin: 0,
  //       snowAccumulationLweSum: 0,
  //       snowAccumulationMax: 0,
  //       snowAccumulationMin: 0,
  //       snowAccumulationSum: 0,
  //       snowIntensityAvg: 0,
  //       snowIntensityMax: 0,
  //       snowIntensityMin: 0,
  //       sunriseTime: "2023-12-14T06:07:00Z",
  //       sunsetTime: "2023-12-14T17:54:00Z",
  //       temperatureApparentAvg: 27.63,
  //       temperatureApparentMax: 32.58,
  //       temperatureApparentMin: 22.66,
  //       temperatureAvg: 27.65,
  //       temperatureMax: 33.72,
  //       temperatureMin: 22.66,
  //       uvHealthConcernAvg: 1,
  //       uvHealthConcernMax: 3,
  //       uvHealthConcernMin: 0,
  //       uvIndexAvg: 2,
  //       uvIndexMax: 8,
  //       uvIndexMin: 0,
  //       visibilityAvg: 17.32,
  //       visibilityMax: 24.14,
  //       visibilityMin: 9.1,
  //       weatherCodeMax: 1000,
  //       weatherCodeMin: 1000,
  //       windDirectionAvg: 170.5,
  //       windGustAvg: 3.14,
  //       windGustMax: 5.16,
  //       windGustMin: 1.11,
  //       windSpeedAvg: 1.34,
  //       windSpeedMax: 2.67,
  //       windSpeedMin: 0.34,
  //     },
  //   },
  //   {
  //     time: "2023-12-15T06:00:00Z",
  //     values: {
  //       cloudBaseAvg: 0.97,
  //       cloudBaseMax: 2.31,
  //       cloudBaseMin: 0,
  //       cloudCeilingAvg: 0.15,
  //       cloudCeilingMax: 3.5,
  //       cloudCeilingMin: 0,
  //       cloudCoverAvg: 32.59,
  //       cloudCoverMax: 72.69,
  //       cloudCoverMin: 0.37,
  //       dewPointAvg: 18.64,
  //       dewPointMax: 20.95,
  //       dewPointMin: 14.89,
  //       evapotranspirationAvg: 0.205,
  //       evapotranspirationMax: 0.685,
  //       evapotranspirationMin: 0.021,
  //       evapotranspirationSum: 4.708,
  //       freezingRainIntensityAvg: 0,
  //       freezingRainIntensityMax: 0,
  //       freezingRainIntensityMin: 0,
  //       humidityAvg: 59.22,
  //       humidityMax: 86.1,
  //       humidityMin: 29.6,
  //       iceAccumulationAvg: 0,
  //       iceAccumulationLweAvg: 0,
  //       iceAccumulationLweMax: 0,
  //       iceAccumulationLweMin: 0,
  //       iceAccumulationLweSum: 0,
  //       iceAccumulationMax: 0,
  //       iceAccumulationMin: 0,
  //       iceAccumulationSum: 0,
  //       moonriseTime: "2023-12-15T08:26:56Z",
  //       moonsetTime: "2023-12-15T20:31:53Z",
  //       precipitationProbabilityAvg: 0,
  //       precipitationProbabilityMax: 0,
  //       precipitationProbabilityMin: 0,
  //       pressureSurfaceLevelAvg: 980.24,
  //       pressureSurfaceLevelMax: 982.71,
  //       pressureSurfaceLevelMin: 977.55,
  //       rainAccumulationAvg: 0,
  //       rainAccumulationLweAvg: 0,
  //       rainAccumulationLweMax: 0,
  //       rainAccumulationLweMin: 0,
  //       rainAccumulationMax: 0,
  //       rainAccumulationMin: 0,
  //       rainAccumulationSum: 0,
  //       rainIntensityAvg: 0,
  //       rainIntensityMax: 0,
  //       rainIntensityMin: 0,
  //       sleetAccumulationAvg: 0,
  //       sleetAccumulationLweAvg: 0,
  //       sleetAccumulationLweMax: 0,
  //       sleetAccumulationLweMin: 0,
  //       sleetAccumulationLweSum: 0,
  //       sleetAccumulationMax: 0,
  //       sleetAccumulationMin: 0,
  //       sleetIntensityAvg: 0,
  //       sleetIntensityMax: 0,
  //       sleetIntensityMin: 0,
  //       snowAccumulationAvg: 0,
  //       snowAccumulationLweAvg: 0,
  //       snowAccumulationLweMax: 0,
  //       snowAccumulationLweMin: 0,
  //       snowAccumulationLweSum: 0,
  //       snowAccumulationMax: 0,
  //       snowAccumulationMin: 0,
  //       snowAccumulationSum: 0,
  //       snowIntensityAvg: 0,
  //       snowIntensityMax: 0,
  //       snowIntensityMin: 0,
  //       sunriseTime: "2023-12-15T06:07:00Z",
  //       sunsetTime: "2023-12-15T17:54:00Z",
  //       temperatureApparentAvg: 28.88,
  //       temperatureApparentMax: 36.07,
  //       temperatureApparentMin: 23.02,
  //       temperatureAvg: 28.63,
  //       temperatureMax: 36,
  //       temperatureMin: 23.02,
  //       uvHealthConcernAvg: 1,
  //       uvHealthConcernMax: 3,
  //       uvHealthConcernMin: 0,
  //       uvIndexAvg: 2,
  //       uvIndexMax: 8,
  //       uvIndexMin: 0,
  //       visibilityAvg: 24.06,
  //       visibilityMax: 24.14,
  //       visibilityMin: 22.43,
  //       weatherCodeMax: 1000,
  //       weatherCodeMin: 1000,
  //       windDirectionAvg: 172.45,
  //       windGustAvg: 2.99,
  //       windGustMax: 5.86,
  //       windGustMin: 1.37,
  //       windSpeedAvg: 1.78,
  //       windSpeedMax: 2.79,
  //       windSpeedMin: 0.68,
  //     },
  //   },
  //   {
  //     time: "2023-12-16T06:00:00Z",
  //     values: {
  //       cloudBaseAvg: 0.27,
  //       cloudBaseMax: 2.19,
  //       cloudBaseMin: 0,
  //       cloudCeilingAvg: 0,
  //       cloudCeilingMax: 0,
  //       cloudCeilingMin: 0,
  //       cloudCoverAvg: 37.47,
  //       cloudCoverMax: 71.31,
  //       cloudCoverMin: 17.76,
  //       dewPointAvg: 18.19,
  //       dewPointMax: 20.49,
  //       dewPointMin: 15.23,
  //       evapotranspirationAvg: 0.349,
  //       evapotranspirationMax: 0.622,
  //       evapotranspirationMin: 0.02,
  //       evapotranspirationSum: 2.788,
  //       freezingRainIntensityAvg: 0,
  //       freezingRainIntensityMax: 0,
  //       freezingRainIntensityMin: 0,
  //       humidityAvg: 51.03,
  //       humidityMax: 87.38,
  //       humidityMin: 32.48,
  //       iceAccumulationAvg: 0,
  //       iceAccumulationLweAvg: 0,
  //       iceAccumulationLweMax: 0,
  //       iceAccumulationLweMin: 0,
  //       iceAccumulationLweSum: 0,
  //       iceAccumulationMax: 0,
  //       iceAccumulationMin: 0,
  //       iceAccumulationSum: 0,
  //       moonriseTime: "2023-12-16T09:24:20Z",
  //       moonsetTime: "2023-12-16T21:32:21Z",
  //       precipitationProbabilityAvg: 0,
  //       precipitationProbabilityMax: 0,
  //       precipitationProbabilityMin: 0,
  //       pressureSurfaceLevelAvg: 980.57,
  //       pressureSurfaceLevelMax: 982.09,
  //       pressureSurfaceLevelMin: 977.1,
  //       rainAccumulationAvg: 0,
  //       rainAccumulationLweAvg: 0,
  //       rainAccumulationLweMax: 0,
  //       rainAccumulationLweMin: 0,
  //       rainAccumulationMax: 0,
  //       rainAccumulationMin: 0,
  //       rainAccumulationSum: 0,
  //       rainIntensityAvg: 0,
  //       rainIntensityMax: 0,
  //       rainIntensityMin: 0,
  //       sleetAccumulationAvg: 0,
  //       sleetAccumulationLweAvg: 0,
  //       sleetAccumulationLweMax: 0,
  //       sleetAccumulationLweMin: 0,
  //       sleetAccumulationLweSum: 0,
  //       sleetAccumulationMax: 0,
  //       sleetAccumulationMin: 0,
  //       sleetIntensityAvg: 0,
  //       sleetIntensityMax: 0,
  //       sleetIntensityMin: 0,
  //       snowAccumulationAvg: 0,
  //       snowAccumulationLweAvg: 0,
  //       snowAccumulationLweMax: 0,
  //       snowAccumulationLweMin: 0,
  //       snowAccumulationLweSum: 0,
  //       snowAccumulationMax: 0,
  //       snowAccumulationMin: 0,
  //       snowAccumulationSum: 0,
  //       snowIntensityAvg: 0,
  //       snowIntensityMax: 0,
  //       snowIntensityMin: 0,
  //       sunriseTime: "2023-12-16T06:08:00Z",
  //       sunsetTime: "2023-12-16T17:55:00Z",
  //       temperatureApparentAvg: 31.25,
  //       temperatureApparentMax: 34.55,
  //       temperatureApparentMin: 22.73,
  //       temperatureAvg: 30.49,
  //       temperatureMax: 34.11,
  //       temperatureMin: 22.73,
  //       visibilityAvg: 24.13,
  //       visibilityMax: 24.14,
  //       visibilityMin: 24.13,
  //       weatherCodeMax: 1100,
  //       weatherCodeMin: 1100,
  //       windDirectionAvg: 210.18,
  //       windGustAvg: 2.06,
  //       windGustMax: 2.72,
  //       windGustMin: 1.31,
  //       windSpeedAvg: 1.52,
  //       windSpeedMax: 1.68,
  //       windSpeedMin: 1.13,
  //     },
  //   },
  // ];

  const handleRefresh = () => {
    setRefreshing(true);
    console.log("Refresh daily forecast");
    //dispatch store action to trigger api middleware that fetches weather data
    setTimeout(() => {
      setRefreshing(false);
    }, 3000);
  };

  const handleScrollToTop = () => {
    listRef.current.scrollToIndex({
      animated: true,
      index: 0,
      viewPosition: 1,
    });
  };
  return (
    <>
    
    {forecast.length > 0 ? (
  <View className="dark:bg-black pt-24">
      <FlatList
        data={forecast}
        ref={listRef}
        renderItem={({ item, index }) => (
          <DailyForecast forecast={item} key={index} />
        )}
        refreshing={refreshing}
        refreshControl={
          <RefreshControl onRefresh={handleRefresh} refreshing={refreshing} />
        }
        onScroll={({ nativeEvent }) => {
          if (nativeEvent.contentOffset.y > 0 && !fabVisible) {
            setFabVisible(true);
          } else if (nativeEvent.contentOffset.y <= 0 && fabVisible) {
            setFabVisible(false);
          }
        }}
        ListHeaderComponent={
          <AppText className="text-center text-2xl my-2">
            Daily Forecast
          </AppText>
        }
        ListEmptyComponent={
          <View>
            <AppText className="text-center">
              Sorry! Please refresh to get latest forecast.
            </AppText>
          </View>
        }
      />
    <FAB
    icon={{ name: "keyboard-arrow-up", color: "white" }}
    size="large"
    visible={fabVisible}
    onPress={handleScrollToTop}
    // placement="right"
    style={{ position: "absolute", bottom: 20, right: 40 }}
    />
  </View>
    ) : <AppText className="text-center" style={{alignSelf: 'center'}} >Sorry! No daily forecasts to show.</AppText>}
    </>
  );
}

const styles = StyleSheet.create({});
